### ISSUE TITLE
Ensure Recovered Accounts are Enabled

### ISSUE THREAD

**Issue by mbillow** [ComputerScienceHouse/self-service#1]
Them knowing their password doesn't help if their account is still disabled.

**Comment by com6056** [comment]
We should make sure we don't allow people that failed to just recover their accounts.

**Comment by mbillow** [comment]
@com6056 That should be addressed by #3. They shouldn't even be able to see the form.

**Comment by mbillow** [comment]
Fixed by 7b0a1db
