### ISSUE TITLE
Use a more robust provider for SMS OTP verification

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/self-service#15]
Instead of depending on email-to-SMS gateways, we should probably just use a real programmable SMS provider such as Twilio to send the OTP verification text messages. With Twilio's current pricing ($0.0075/msg), we can send 1,333 text messages for $10. We could also email them and see if they can give us some credit to mess around with for free.

**Comment by mbillow** [comment]
Done in #26
